name: GraalVM build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OCI_CLI_USER:            ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY:         ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT:     ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT:     ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION:          ${{ secrets.OCI_CLI_REGION }}
      OCI_DOCKER_REPO:         ${{ secrets.OCI_DOCKER_REPO }}
      OCI_AUTH_TOKEN:          ${{ secrets.OCI_AUTH_TOKEN }}
      OCI_COMPARTMENT_OCID:    ${{ secrets.OCI_COMPARTMENT_OCID }}
      OCI_CLUSTER_OCID:        ${{ secrets.OCI_CLUSTER_OCID }}

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Java version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version || true

      - name: Extract configuration files
        run: |
          cd MtdrSpring
          wget "${{ secrets.OCI_PAR_URL }}"
          tar -xzvf deployment_config.tgz
          source env.sh
          cat at.cfg | docker login -u "axvik3xzohce/a00836080@tec.mx" --password-stdin mx-queretaro-1.ocir.io

      - name: Get or create OCIR repo
        id: get-ocir
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: reacttodo/asdvp
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
          
      - name: Restore backend config files
        run: |
          cd MtdrSpring/backend/src/main/resources
          echo "${{ secrets.APP_PROPS_B64 }}" | base64 -d > application.properties
          echo "${{ secrets.SPRING_YAML_B64 }}" | base64 -d > todolistapp-springboot.yaml
          echo "✅ Restored application.properties and todolistapp-springboot.yaml"
      
      - name: UnDeploy
        run: |
          cd MtdrSpring
          source env.sh
          (cd backend; source undeploy.sh)

      - name: Build backend
        env:
          CI: false
        run: |
          cd MtdrSpring
          source env.sh
          (cd backend; source build.sh)

      - name: Configure kubectl for OKE
        id: kubectl-oke-action
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        with:
          cluster: ${{ secrets.OCI_CLUSTER_OCID }}
      - name: Deploy
        run: |
          cd MtdrSpring
          source env.sh
          (cd backend; source deploy.sh)
