# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: [ main,  testing ]
  pull_request:
    branches: [ main, testing ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          FILTER_REGEX_EXCLUDE: (.*\.sh$|node_modules|target|build|dist|coverage|\.idea|\.vscode|\.mvn|out|generated|mocks|.*\.ps1$|.*\.tf$)
          
